WIP: Making the project count all the words in the document
I am receiving an error:
```
line 15, in <module>
    dic[word] = 1
TypeError: unhashable type: 'list'
```
I hope to get this running soon but after this i will need to distinguish from punctuation.